language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 2.7
      language: python
      env: EXTRA_PACKAGES="python-scipy"
    - compiler: clang
      python: 3.3
      language: python
      env: EXTRA_PACKAGES="python3-scipy"
    - compiler: clang
      rvm: 1.8.7
      language: ruby
      env: CUSTOM_PKG="gem install narray"
    - compiler: clang
      language: objective-c
      env: CUSTOM_PKG="brew update" OSX=1
virtualenv:
  system_site_packages: true
before_install:
 - if [ -z $OSX ] ; then sudo apt-get update -qq ; else ; brew update ; fi
 - if [ -z $OSX ] ; then sudo apt-get install -qq cmake libatlas3gf-base libatlas-dev liblapack-dev $EXTRA_PACKAGES ; fi
 - mkdir build
 - cd build
 - $CUSTOM_PKG
 - cmake -DCMAKE_PREFIX_PATH=$PREFIX ../
