language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 3.3
      language: python
      env: CUSTOM_PKG="pip install -q numpy; pip install jinja2"
    - compiler: clang
      language: ruby
      rvm: 1.8.7
      env: CUSTOM_PKG="gem install narray"
virtualenv:
  system_site_packages: true
before_install:
 - if [ -z $OSX ] ; then sudo apt-get update -qq ; else brew update ; fi
 - if [ -z $OSX ] ; then sudo apt-get install -qq cmake libatlas3gf-base libatlas-dev liblapack-dev $EXTRA_PACKAGES ; fi
 - mkdir build
 - cd build
 - $CUSTOM_PKG
 - cmake -DCMAKE_PREFIX_PATH=$PREFIX ../
 - echo $RUBYLIB
 - export RUBYLIB=$RUBYLIB:/tt
