language: cpp
python:
 - 2.7
 - 3.3
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 2.7
    - compiler: clang
      python: 3.3
before_install:
 - sudo apt-get update -qq
 - python --version
 - sudo pip install numpy scipy --use-mirrors
