compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 2.7
      language: python
    - compiler: clang
      python: 3.3
      language: python
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libatlas3gf-base libatlas-dev liblapack-dev
 - python --version
 - echo $TRAVIS_PYTHON_VERSION
 - mkdir build
 - cd build
 - cmake ../
 - sudo pip install numpy scipy --use-mirrors
