language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 3.3
      language: python
      env: EXTRA_PACKAGES="python3-scipy"
    - compiler: clang
      language: objective-c
      env: CUSTOM_PKG="brew update" OSX=1
virtualenv:
  system_site_packages: true
before_install:
 - if [ -z $OSX ] ; then sudo apt-get update -qq ; else brew update ; fi
 - if [ -z $OSX ] ; then sudo apt-get install -qq cmake libatlas3gf-base libatlas-dev liblapack-dev $EXTRA_PACKAGES ; fi
 - if [ $OSX ] ; then curl -O https://raw.github.com/rudix-mac/package-manager/master/rudix.py && sudo python rudix.py install rudix && sudo rudix install jinja2 ; fi
 - mkdir build
 - cd build
 - $CUSTOM_PKG
 - cmake -DCMAKE_PREFIX_PATH=$PREFIX ../
