language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 3.3
      language: python
      env: CUSTOM_PKG="pip install numpy"
    - compiler: clang
      language: ruby
      rvm: 1.8.7
      env: CUSTOM_PKG="gem install narray"
virtualenv:
  system_site_packages: true
before_install:
 - if [ -z $OSX ] ; then sudo apt-get update -qq ; else brew update ; fi
 - if [ -z $OSX ] ; then sudo apt-get install -qq libbz2-dev cdbs libarpack2-dev libatlas-base-dev libblas-dev libglpk-dev libhdf5-serial-dev zlib1g-dev libxml2-dev libreadline6-dev libreadline-dev libsnappy-dev liblzo2-dev liblzma-dev liblapack-dev gdb cmake python-jinja2 $EXTRA_PACKAGES ; fi
 - mkdir build
 - cd build
 - $CUSTOM_PKG
 - cmake -DCMAKE_PREFIX_PATH=$PREFIX ../
 - echo $RUBYLIB
 - export RUBYLIB=$RUBYLIB:/tt
