language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 2.7
    - compiler: clang
      python: 3.3
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libatlas3gf-base libatlas-dev liblapack-dev
 - python --version
 - echo $TRAVIS_PYTHON_VERSION
 - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ] ; then python3 --version ; fi
 - sudo pip install numpy scipy --use-mirrors
