language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 3.3
      language: python
      env:
      - PIP_ARGS=" -I --use-wheel --find-links=http://cache27diy-cpycloud.rhcloud.com/3.3/"
      - CUSTOM_PKG=`echo $TRAVIS_PYTHON_VERSION`
    - compiler: clang
      language: ruby
      rvm: 1.9.3
      env: CUSTOM_PKG="gem install nmatrix"
before_install:
 - eval $CUSTOM_PKG
 - echo $TRAVIS_PYTHON_VERSION
script:
 - cmake -DCMAKE_PREFIX_PATH=$PREFIX ../
 - echo $CUSTOM_PKG
