language: cpp
compiler:
  - gcc
  - clang
matrix:
  include:
    - compiler: clang
      python: 2.7
      language: python
    - compiler: clang
      python: 3.3
      language: python
      env: PREFIX="~/virtualenv/python3.3/"
    - compiler: clang
      ruby: 1.8.7
      language: ruby
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libatlas3gf-base libatlas-dev liblapack-dev
 - python --version
 - echo $TRAVIS_PYTHON_VERSION
 - mkdir build
 - cd build
 - cmake -DCMAKE_PREFIX_PATH=${PREFIX} ../
 - sudo pip install numpy scipy --use-mirrors
